services:
  nodesvr:
    # with default image from hub
    image: node:latest
    container_name: nodesvr_demo
    restart: always
    command: sh -c "npm install && npm run serve"
    ports:
      - 3001:3000
    working_dir: /app
    volumes:
      - ./svr:/app
  web:
    # with dockerfile
    build: ./web
    container_name: nginx_web
    restart: always
    ports:
      - 3000:80